version: "3.5"

services:
  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nestjs:
    build:
      context: ./packages/server
      dockerfile: Dockerfile.dev
    env_file:
     - ./packages/server/.env.dev
    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./packages/server/:/app

  react_app:
    build:
      context: ./packages/client
      dockerfile: Dockerfile.dev
    env_file:
     - ./packages/client/.env.dev
    ports:
      - 3000:3000
    volumes:
      - ./packages/client/:/app

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db

  openapi_generator:
    build:
      context: ./tools/openapi-generator
      dockerfile: Dockerfile
    depends_on:
      - nestjs
    volumes:
      - ./tools/openapi-generator/.build:/local/out

